name = "TiggerHat Doks"
baseURL = 'https://tiggerhat.github.io/'
license = "MIT"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "Hugo theme helping you build modern documentation websites that are secure, fast, and SEO-ready — by default."

homepage = "https://tiggerhat.github.io"
demosite = "https://tiggerhat.github.io"

tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]

[author]
  name = "TiggerHat"
  homepage = "https://tiggerhat.github.io"
